### ISSUE TITLE
Error starting DAVIS dataset from davisinteractive.dataset import Davis

### ISSUE THREAD

**Issue by scaelles** [albertomontesg/davis-interactive#25]
Traceback (most recent call last):
  File "/home/csergi/scratch/pytorch/Scribble-OSVOS/demo_interactive.py", line 31, in <module>
    davis = Davis(davis_root=Path.db_root_dir())
  File "/home/csergi/miniconda3/envs/interactive/lib/python3.6/site-packages/davisinteractive/dataset/davis.py", line 61, in __init__
    'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/csergi/miniconda3/envs/interactive/lib/python3.6/site-packages/davisinteractive/dataset/davis.json'

**Comment by albertomontesg** [comment]
Solved
