### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by zanglam** [albertomontesg/davis-interactive#59]
I tried to use the provided package to evaluate my method on test-dev dataset, but errors arose as below:

```
Traceback (most recent call last):
  File "interactive_testdev.py", line 256, in <module>
    run_interactive()
  File "interactive_testdev.py", line 231, in run_interactive
    sess.submit_masks(pred_masks)
  File "....../davisinteractive/session/session.py", line 317, in submit_masks
    next_scribble_frame_candidates=next_scribble_frame_candidates)
  File "....../davisinteractive/connector/remote.py", line 129, in post_predicted_masks
    response = r.json()
  File "....../requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "....../json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "....../json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "....../json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I tried several times, but error occurred every time(in different videos). 

In "davisinteractive/connector/remote.py", I found code:
```
    def post_predicted_masks(self,
                             sequence,
                             scribble_idx,
                             pred_masks,
                             timing,
                             interaction,
                             next_scribble_frame_candidates=None):
        .......
        self._handle_response(r, raise_error=True)
        response = r.json() # line 129, where error raised
        return response

......

    def _handle_response(self, response, raise_error=False):
        ......
        if response.status_code == 200:
            try:
                response.json()
            except json.decoder.JSONDecodeError:
                logging.error(response.content)
        return False
```
It seems that when a JSONDecodeError occurs, line 129(response = r.json()) will still be executed and error raised.
What might be the reasons for such a problem and how can I avoid it.

**Comment by scaelles** [comment]
Hello zanglam,

We are aware of the problem and we are currently debugging it, we'll notify you when it's fixed.

**Comment by zanglam** [comment]
Thanks for your reply.
I guess this is due to the instability of the network connection since I've just get a similar error as below:
```
[0.23578103753183455, 0.4536872112805292], [0.23572439224152708, 0.45392076140703375], [0.2356674320607901, 0.45415431291118025], [0.2356101634819134, 0.4543878656885614], [0.23555259330202197, 0.4546214196419274], [0.23549472861866655, 0.4548549746807572], [0.23543657682490632, 0.45508853072085037], [0.23537814560387357, 0.4553220876839391], [0.2353194429228231, 0.45555564549732047], [0.23526047702666653, 0.4557892040935068], [0.2352012564309921, 0.4560227634098951], [0.23514178991457452, 0.4562563233884528], [0.23508208651138113, 0.4564898839754219], [0.2350221555020779, 0.45672344512103963], [0.23496200640504908, 0.45695700677927065], [0.23490164896693416, 0.4571905689075609], [0.2348410931527005, 0.4574241314665993], [0.23478034913526008, 0.45765769442009785], [0.23471942728464756, 0.45789125773458067], [0.23465833815677656, 0.45812482137919014], [0.23459709248179134, 0.4583583853255003], [0.2345357011520333, 0.4585919495473452], [0.23447417520964528, 0.4588255140206556], [0.23441252583383382, 0.45905907872330626], [0.23435076432781404, 0.4592926436349749], [0.23428890210546374, 0.4595262087370072], [0.23422695067771113, 0.45975977401229307], [0.23416492163868358, 0.45999333944515], [0.23410282665164966, 0.460226905021214], [0.23404067743477794, 0.46046047072'
Traceback (most recent call last):
  File "interactive_testdev.py", line 256, in <module>
    run_interactive()
  File "interactive_testdev.py", line 231, in run_interactive
    sess.submit_masks(pred_masks)
  File "....../davisinteractive/session/session.py", line 317, in submit_masks
    next_scribble_frame_candidates=next_scribble_frame_candidates)
  File "....../davisinteractive/connector/remote.py", line 129, in post_predicted_masks
    response = r.json()
  File "....../requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "....../json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "....../json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "....../json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 791169 (char 791168)
```
It looks like that the received response content is incomplete.
I hope the above information is helpful for debugging.

**Comment by scaelles** [comment]
Hello zanglam,

Thanks for your help. The json file is empty because the server is unreachable and then the response returns a 502 Bad Gateway error message. We are trying to figure why the server is sometimes unavailable and we hope to have a fix today or tomorrow.

Apologies for the inconvenience.

**Comment by albertomontesg** [comment]
Hello @zanglam,

We figure it out which was the problem. It was not that the server was unreachable. For serving the infrastructure we use Django with guinocorn workers to handle the requests. As this year we are computing the J&F and not only the Jaccard, it means the evaluation computations take a little bit more times. What happened is that some requests for sequences with more objects (like salsa) were hitting the timeout set by guinocorn for a worker to handle the request. If the request was not handled in 30s (the default timeout) the response would have 502 status code, which is what you were hitting.

Right now the server is updated with a larger timeout and should be able to handle your interactive sessions. I would like to apologize for any inconvenience this disruption may have cause you. 

Thank you very much for your understanding!

**Comment by zanglam** [comment]
Hello @albertomontesg ,

Thank you very much for fixing the problem so quickly. I haven't encountered the same problem again. But I'm being troubled by another problem:
```
Traceback (most recent call last):
  File "new_interactive_testdev.py", line 511, in <module>
    run_interactive()
  File "new_interactive_testdev.py", line 485, in run_interactive
    sess.submit_masks(pred_masks)
  File "......./davisinteractive/session/session.py", line 317, in submit_masks
    next_scribble_frame_candidates=next_scribble_frame_candidates)
  File "....../davisinteractive/connector/remote.py", line 127, in post_predicted_masks
    headers=self.headers)
  File "....../requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "....../requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "....../requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "....../requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
The connection error(sometimes it is "('Connection broken: OSError("(104, \'ECONNRESET\')",)', OSError("(104, 'ECONNRESET')",))") occurred so frequently that I haven't made a submission successfully yet(best case: finish evaluating about 88% samples). I wonder if there is a way to alleviate this problem. Thank you.

**Comment by albertomontesg** [comment]
Can we get a sample of your code you use to make the submission, so probably we try to understand more the user case and probably spot anything useful to solve this issue. You can send us a sample here or by mailing it privately.

**Comment by zanglam** [comment]
Hello @albertomontesg ,
Sorry for the delayed response. 
I run my code on another machine(the internet connection is somehow stabler) and it works fine and I've successfully submitted my results. Thank you anyways!
