### ISSUE TITLE
ValueError: Davis root folder must be named "DAVIS"

### ISSUE THREAD

**Issue by be-redAsmara** [albertomontesg/davis-interactive#61]
Traceback (most recent call last):
  File "/home/bereket/Desktop/IRCAD-Data/MiVOS/MiVOS-MiVOS-STCN/eval_interactive_davis.py", line 77, in <module>
    with DavisInteractiveSession(davis_root=davis_path+'/trainval', report_save_dir='../output', max_nb_interactions=8, max_time=8*30) as sess:
  File "/home/bereket/anaconda3/envs/mivos/lib/python3.9/site-packages/davisinteractive/session/session.py", line 89, in __enter__
    samples, max_t, max_i = self.connector.start_session(
  File "/home/bereket/anaconda3/envs/mivos/lib/python3.9/site-packages/davisinteractive/connector/local.py", line 29, in start_session
    self.service = EvaluationService(davis_root=davis_root)
  File "/home/bereket/anaconda3/envs/mivos/lib/python3.9/site-packages/davisinteractive/evaluation/service.py", line 27, in __init__
    self.davis = Davis(davis_root=davis_root)
  File "/home/bereket/anaconda3/envs/mivos/lib/python3.9/site-packages/davisinteractive/dataset/davis.py", line 93, in __init__
    raise ValueError('Davis root folder must be named "DAVIS"')
ValueError: Davis root folder must be named "DAVIS"

I am running into this issue?

**Comment by scaelles** [comment]
Hello,

Thanks for using the Davis interactive package! In order to run the package, you also have to download the Davis dataset, please see instructions [here](https://github.com/albertomontesg/davis-interactive/blob/master/docs/pages/user_guide/installation.md#davis-dataset).
